# PR pipeline
variables: 
- group: state-data
- name: service-connection
  value: 'yor'

trigger:
  branches:
    exclude:
      - main

stages:
- stage: validate
  displayName: Validation
  condition: eq(variables['Build.Reason'], 'PullRequest')
  jobs:
  - job: Validate
    displayName: Validate Terraform
    pool: yor
    steps:
    - task: TerraformInstaller@0
      displayName: Install Terraform
      inputs:
        terraformVersion: 'latest'
    - script: | 
        terraform fmt -check
        echo "displayName: Terraform Format Check"
    - script: |
        terraform init -backend=false
        echo "displayName: Terraform Init"
    - script: |
        terraform validate
        echo "displayName: Terraform Validate"

- stage: Plan
  displayName: Plan
  condition: eq(variables['Build.Reason'], 'PullRequest')
  jobs:
  - job: Plan
    pool: yor
    steps:
    - task: TerraformInstaller@0
      displayName: Install Terraform
      inputs:
        terraformVersion: 'latest'
    
    - task: TerraformTaskV4@4
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: $(service-connection)
        backendAzureRmResourceGroupName: '$(BACKEND_RESOURCE_GROUP_NAME)'
        backendAzureRmStorageAccountName: '$(BACKEND_AZURE_STORAGE_ACCOUNT_NAME)'
        backendAzureRmContainerName: '$(BACKEND_AZURE_STORAGE_ACCOUNT_CONTAINER_NAME)'
        backendAzureRmKey: '$(BACKEND_AZURE_STORAGE_ACCOUNT_KEY_NAME)'
      env:
        ARM_CLIENT_ID: '$(BACKEND_CLIENT_ID)'
        ARM_CLIENT_SECRET: '$(BACKEND_CLIENT_SECRET)'
        ARM_SUBSCRIPTION_ID: '$(BACKEND_SUBSCRIPTION_ID)'
        ARM_TENANT_ID: '$(BACKEND_TENANT_ID)'
        TF_IN_AUTOMATION: true
        TF_INPUT: 0
        TF_LOG: INFO
    - script: |
        curl -s -k https://api.github.com/repos/bridgecrewio/yor/releases/latest | jq '.assets[] | select(.name | contains("linux_386")) | select(.content_type | contains("gzip")) | .browser_download_url' -r | awk '{print "curl -L -k " $0 " -o yor.tar.gz"}' | sh
        sudo tar -xf yor.tar.gz -C /usr/bin/ 
        rm yor.tar.gz 
        sudo chmod +x /usr/bin/yor 
        echo 'alias yor="/usr/bin/yor"' >> ~/.bashrc
        yor --version
    - script: |
        yor tag --directory .
    - task: TerraformTaskV4@4
      displayName: Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        commandOptions: -out=$(System.DefaultWorkingDirectory)/deploy.tfplan
        environmentServiceNameAzureRM: $(service-connection)
      env:
        ARM_CLIENT_ID: '$(BACKEND_CLIENT_ID)'
        ARM_CLIENT_SECRET: '$(BACKEND_CLIENT_SECRET)'
        ARM_SUBSCRIPTION_ID: '$(BACKEND_SUBSCRIPTION_ID)'
        ARM_TENANT_ID: '$(BACKEND_TENANT_ID)'
        TF_IN_AUTOMATION: true
        TF_INPUT: 0
        TF_LOG: INFO
    # Push plan file to Azure Storage Account for Apply
    - task: PublishPipelineArtifact@1
      displayName: Publish Plan File as an artifact
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/deploy.tfplan'
        artifactName: PlanFile
        publishLocation: 'pipeline'
